import { RIDGES } from "@/lib/ambient/terrain";

/**
 * The brushes.
 *
 * This is the part that answers "why doesn't it look like SVG". Clean geometry
 * is generated by `lib/ambient/*`, and then every mass in the scene is pushed
 * through one of these filters before it reaches the screen. Nothing in the
 * painting is drawn with the edge it was authored with.
 *
 * Each filter is some combination of three ideas:
 *
 * 1. **Displacement = a hand.** `feTurbulence` → `feDisplacementMap` warps the
 *    outline of a shape along a smooth noise field. A bezier that was
 *    mathematically perfect comes out wobbling by a few pixels, unevenly, the
 *    way a loaded brush wobbles. This single step is what kills the vector look
 *    and it is why nothing here needed to be hand-drawn.
 * 2. **A second, much finer turbulence = pigment.** Multiplied back over the
 *    shape, it makes the fill uneven — thin in places, pooled in others — so no
 *    surface in the scene is a flat colour.
 * 3. **A little blur = distance.** Bound into the same filter rather than
 *    applied separately, so a far ridge costs exactly one filter, not two.
 *
 * The scale of (1) and the amount of (3) come from the layer's `depth`. Far
 * things get almost no wobble and a lot of softness; near things get a big
 * ragged edge and stay sharp. That is atmospheric perspective expressed as
 * brushwork rather than as colour, and it is doing as much of the depth work as
 * the palette is.
 *
 * **Performance note for future sessions:** every filter here is static. No
 * primitive's attributes are ever animated, which means the browser rasterises
 * each filtered group once and then only ever re-composites it — animation in
 * this scene is exclusively `transform` and `opacity` on already-painted
 * layers. Animating a `baseFrequency` would re-run all of this every frame and
 * is the one change guaranteed to make the backdrop expensive.
 */
export function PaintFilters() {
  return (
    <svg
      aria-hidden
      width="0"
      height="0"
      // Not `display: none` — filters defined inside a display:none subtree
      // fail to resolve in some engines.
      style={{ position: "absolute", width: 0, height: 0, overflow: "hidden" }}
    >
      <defs>
        {/* One brush per ridge, tuned by depth. */}
        {RIDGES.map((ridge, index) => (
          <filter
            key={ridge.id}
            id={`brush-${ridge.id}`}
            x="-6%"
            y="-14%"
            width="112%"
            height="132%"
            colorInterpolationFilters="sRGB"
          >
            <feTurbulence
              type="fractalNoise"
              baseFrequency={`${0.006 + index * 0.0015} ${0.017 + index * 0.004}`}
              numOctaves={3}
              seed={11 + index * 7}
              result="warp"
            />
            <feDisplacementMap
              in="SourceGraphic"
              in2="warp"
              // Near ridges get a big ragged edge; the far range barely moves,
              // because at that distance an edge is haze, not brushwork.
              scale={3 + (1 - ridge.depth) * 13}
              xChannelSelector="R"
              yChannelSelector="G"
              result="edge"
            />
            <feTurbulence
              type="fractalNoise"
              baseFrequency="0.42"
              numOctaves={3}
              seed={31 + index * 5}
              result="tooth"
            />
            <feColorMatrix
              in="tooth"
              type="matrix"
              // Constant mid-grey, with the noise driving alpha only.
              values={`0 0 0 0 0.68  0 0 0 0 0.66  0 0 0 0 0.6  0 0 0 ${0.42 - ridge.depth * 0.3} 0`}
              result="toothTint"
            />
            <feComposite in="toothTint" in2="edge" operator="in" result="grain" />
            <feBlend in="edge" in2="grain" mode="multiply" result="painted" />
            <feGaussianBlur
              in="painted"
              stdDeviation={Math.round((0.4 + ridge.depth * ridge.depth * 4) * 10) / 10}
            />
          </filter>
        ))}

        {/*
         * Touch-device counterparts of the ridge brushes above, swapped in by
         * the `(pointer: coarse)` rule at the bottom of globals.css. Same warp
         * and blur — the silhouette reads the same — with the second
         * `feTurbulence`→`feColorMatrix`→`feComposite`→`feBlend` "tooth" pass
         * dropped. That pass is what gives the fill its pigment texture, and
         * it is a second full-region noise generation on top of the first;
         * `feTurbulence` is the most expensive primitive here, so this is
         * roughly half the cost per ridge for a texture difference nobody
         * reads as "wrong" at meadow scale on a phone screen. See the
         * `(pointer: coarse)` performance note in globals.css for why phones
         * get this and desktop doesn't.
         */}
        {RIDGES.map((ridge, index) => (
          <filter
            key={`${ridge.id}-lite`}
            id={`brush-${ridge.id}-lite`}
            x="-6%"
            y="-14%"
            width="112%"
            height="132%"
            colorInterpolationFilters="sRGB"
          >
            <feTurbulence
              type="fractalNoise"
              baseFrequency={`${0.006 + index * 0.0015} ${0.017 + index * 0.004}`}
              numOctaves={3}
              seed={11 + index * 7}
              result="warp"
            />
            <feDisplacementMap
              in="SourceGraphic"
              in2="warp"
              scale={3 + (1 - ridge.depth) * 13}
              xChannelSelector="R"
              yChannelSelector="G"
              result="edge"
            />
            <feGaussianBlur
              in="edge"
              stdDeviation={Math.round((0.4 + ridge.depth * ridge.depth * 4) * 10) / 10}
            />
          </filter>
        ))}

        {/*
         * Clouds. Two brushes: a coarse one for the built-up parts of a cloud
         * and a very soft one for the shoulders that are supposed to be losing
         * their argument with the sky.
         */}
        <filter id="brush-cloud" x="-18%" y="-30%" width="136%" height="170%" colorInterpolationFilters="sRGB">
          <feTurbulence type="fractalNoise" baseFrequency="0.008 0.014" numOctaves={4} seed={3} result="warp" />
          <feDisplacementMap in="SourceGraphic" in2="warp" scale="26" xChannelSelector="R" yChannelSelector="G" result="edge" />
          <feTurbulence type="fractalNoise" baseFrequency="0.09" numOctaves={4} seed={17} result="tooth" />
          <feColorMatrix
            in="tooth"
            type="matrix"
            values="0 0 0 0 0.86  0 0 0 0 0.84  0 0 0 0 0.8  0 0 0 0.3 0"
            result="toothTint"
          />
          <feComposite in="toothTint" in2="edge" operator="in" result="grain" />
          <feBlend in="edge" in2="grain" mode="multiply" result="painted" />
          <feGaussianBlur in="painted" stdDeviation="2.4" />
        </filter>

        {/* Touch-device counterpart of brush-cloud — see the ridge-lite note above. */}
        <filter id="brush-cloud-lite" x="-18%" y="-30%" width="136%" height="170%" colorInterpolationFilters="sRGB">
          <feTurbulence type="fractalNoise" baseFrequency="0.008 0.014" numOctaves={4} seed={3} result="warp" />
          <feDisplacementMap in="SourceGraphic" in2="warp" scale="26" xChannelSelector="R" yChannelSelector="G" result="edge" />
          <feGaussianBlur in="edge" stdDeviation="2.4" />
        </filter>

        <filter id="brush-vapour" x="-30%" y="-40%" width="160%" height="180%" colorInterpolationFilters="sRGB">
          <feTurbulence type="fractalNoise" baseFrequency="0.011 0.02" numOctaves={4} seed={23} result="warp" />
          <feDisplacementMap in="SourceGraphic" in2="warp" scale="42" xChannelSelector="R" yChannelSelector="G" />
          <feGaussianBlur stdDeviation="11" />
        </filter>

        {/*
         * Foliage. The strongest displacement in the scene: leaf masses should
         * have a genuinely torn silhouette, because a smooth-edged green mass
         * is a shrub icon.
         */}
        <filter id="brush-leaf" x="-16%" y="-16%" width="132%" height="132%" colorInterpolationFilters="sRGB">
          <feTurbulence type="fractalNoise" baseFrequency="0.026 0.034" numOctaves={4} seed={41} result="warp" />
          <feDisplacementMap in="SourceGraphic" in2="warp" scale="17" xChannelSelector="R" yChannelSelector="G" result="edge" />
          <feTurbulence type="fractalNoise" baseFrequency="0.36" numOctaves={4} seed={53} result="tooth" />
          <feColorMatrix
            in="tooth"
            type="matrix"
            values="0 0 0 0 0.66  0 0 0 0 0.64  0 0 0 0 0.56  0 0 0 0.5 0"
            result="toothTint"
          />
          <feComposite in="toothTint" in2="edge" operator="in" result="grain" />
          <feBlend in="edge" in2="grain" mode="multiply" result="painted" />
          <feGaussianBlur in="painted" stdDeviation="0.55" />
        </filter>

        {/* Touch-device counterpart of brush-leaf — see the ridge-lite note above. */}
        <filter id="brush-leaf-lite" x="-16%" y="-16%" width="132%" height="132%" colorInterpolationFilters="sRGB">
          <feTurbulence type="fractalNoise" baseFrequency="0.026 0.034" numOctaves={4} seed={41} result="warp" />
          <feDisplacementMap in="SourceGraphic" in2="warp" scale="17" xChannelSelector="R" yChannelSelector="G" result="edge" />
          <feGaussianBlur in="edge" stdDeviation="0.55" />
        </filter>

        {/* Foreground growth: rough edges, coarse pigment, no softening at all. */}
        <filter id="brush-meadow" x="-10%" y="-16%" width="120%" height="134%" colorInterpolationFilters="sRGB">
          <feTurbulence type="fractalNoise" baseFrequency="0.02 0.05" numOctaves={3} seed={61} result="warp" />
          <feDisplacementMap in="SourceGraphic" in2="warp" scale="4.5" xChannelSelector="R" yChannelSelector="G" result="edge" />
          <feTurbulence type="fractalNoise" baseFrequency="0.5" numOctaves={3} seed={71} result="tooth" />
          <feColorMatrix
            in="tooth"
            type="matrix"
            values="0 0 0 0 0.7  0 0 0 0 0.68  0 0 0 0 0.6  0 0 0 0.45 0"
            result="toothTint"
          />
          <feComposite in="toothTint" in2="edge" operator="in" result="grain" />
          <feBlend in="edge" in2="grain" mode="multiply" />
        </filter>

        {/* Touch-device counterpart of brush-meadow — see the ridge-lite note above. */}
        <filter id="brush-meadow-lite" x="-10%" y="-16%" width="120%" height="134%" colorInterpolationFilters="sRGB">
          <feTurbulence type="fractalNoise" baseFrequency="0.02 0.05" numOctaves={3} seed={61} result="warp" />
          <feDisplacementMap in="SourceGraphic" in2="warp" scale="4.5" xChannelSelector="R" yChannelSelector="G" />
        </filter>

        {/* Undergrowth and cast shadow: soft, formless, sits under everything. */}
        <filter id="brush-shade" x="-20%" y="-40%" width="140%" height="180%" colorInterpolationFilters="sRGB">
          <feTurbulence type="fractalNoise" baseFrequency="0.009 0.024" numOctaves={4} seed={83} result="warp" />
          <feDisplacementMap in="SourceGraphic" in2="warp" scale="30" xChannelSelector="R" yChannelSelector="G" />
          <feGaussianBlur stdDeviation="7" />
        </filter>

        {/* Man-made things get the lightest touch — a path still has to read as
            a path, it just shouldn't read as a vector one. */}
        <filter id="brush-prop" x="-14%" y="-14%" width="128%" height="128%" colorInterpolationFilters="sRGB">
          <feTurbulence type="fractalNoise" baseFrequency="0.03 0.045" numOctaves={3} seed={97} result="warp" />
          <feDisplacementMap in="SourceGraphic" in2="warp" scale="3.2" xChannelSelector="R" yChannelSelector="G" />
          <feGaussianBlur stdDeviation="0.6" />
        </filter>

        {/*
         * Not an edge brush — a colour field. Rendered over the sky as
         * soft-light, this is what stops the sky being a gradient: real
         * watercolour dries in blooms and tidelines, and a clean two-stop ramp
         * is the single most obvious "this was made in a browser" signal.
         */}
        <filter id="sky-wash" x="0%" y="0%" width="100%" height="100%" colorInterpolationFilters="sRGB">
          <feTurbulence type="fractalNoise" baseFrequency="0.0021 0.0055" numOctaves={5} seed={7} result="clouds" />
          <feColorMatrix
            in="clouds"
            type="matrix"
            // White field; the red channel of the noise becomes alpha, biased
            // negative so most of the sky stays clear and only the blooms show.
            values="0 0 0 0 1  0 0 0 0 1  0 0 0 0 1  0.9 0 0 0 -0.32"
          />
        </filter>

        {/* Cloud shoulders dissolve toward the lower left, away from the sun,
            so the lit upper edges survive. */}
        <radialGradient id="cloud-fade" cx="0.62" cy="0.4" r="0.72">
          <stop offset="0.35" stopColor="#fff" />
          <stop offset="0.82" stopColor="#fff" stopOpacity="0.75" />
          <stop offset="1" stopColor="#000" />
        </radialGradient>
        <radialGradient id="cloud-fade-alt" cx="0.44" cy="0.5" r="0.66">
          <stop offset="0.3" stopColor="#fff" />
          <stop offset="0.78" stopColor="#fff" stopOpacity="0.68" />
          <stop offset="1" stopColor="#000" />
        </radialGradient>

        <mask id="cloud-mask" maskUnits="objectBoundingBox" maskContentUnits="objectBoundingBox">
          <rect x="-0.15" y="-0.25" width="1.3" height="1.5" fill="url(#cloud-fade)" />
        </mask>
        <mask id="cloud-mask-alt" maskUnits="objectBoundingBox" maskContentUnits="objectBoundingBox">
          <rect x="-0.15" y="-0.25" width="1.3" height="1.5" fill="url(#cloud-fade-alt)" />
        </mask>
      </defs>
    </svg>
  );
}
