// Generated by scripts/bake-plates.ts — do not edit by hand.
// Lists the depth bands that have baked plates in public/plates/.
// An id absent from this array falls back to its live SVG layer.
import type { PlateId } from "./plates";

export const BAKED_PLATES: readonly PlateId[] = ["sky","far","near","tree","boughs"];

export const PLATE_SCALE = 2;
